# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://andxyz.com
root_url: https://andxyz.com
title: Andrew Stevens » an http request for my thoughts
subtitle:
author: Andrew Stevens
simple_search: https://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# https://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

plugins_dir: plugins

plugins:
  - jekyll-feed

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: https://andxyz.com/atom.xml
subscribe_email: # RSS feeds can list your email address if you like
email:
feed:
  path: atom.xml

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in https://site.com/project set 'root: /project'
root: /
permalink: /writings/:year/:month/:day/:title/
# source: source
# destination: public

code_dir: downloads/code
category_dir: writings/categories

markdown:  kramdown
highlighter: rouge
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  true

liquid:
  error_mode: warn

# paginate: 10          # Posts per page on the blog index
# pagination_dir: writings  # Directory base for pagination URLs eg. /blog/page/2/
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Disqus Comments
disqus_short_name: andxyz
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-3195072-1
